---
- hosts: idrac
  connection: local
  name: Deleting a LC job
  gather_facts: False

  tasks:
  - name: Delete a LC job 
    dellemc_delete_lc_job:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"
       job_id: "JID_123456789"
