---
- name: Converge idrac_gather_facts for NIC
  hosts: all
  gather_facts: false
  vars:
    hostname: "{{ lookup('env', 'IDRAC_IP') }}"
    username: "{{ lookup('env', 'IDRAC_USER') }}"
    password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
    validate_certs: false
    target:
      - NIC
    idrac_gather_facts_uri_method: "GET"
    idrac_gather_facts_uri_headers:
      Accept: "application/json"
      Content-Type: "application/json"
      OData-Version: "4.0"
    idrac_gather_facts_uri_body_format: "json"
    idrac_gather_facts_uri_status_code:
      - 200
      - 400
      - 401
      - 404
      - -1
    idrac_gather_facts_uri_return_content: true
    diff_data: {}
    exclude_keys: []
    api_system: "/redfish/v1/Systems/System.Embedded.1"

  tasks:
    - name: Gather Facts for the NIC component
      ansible.builtin.include_role:
        name: "idrac_gather_facts"

    - name: Assert nic dict for length
      ansible.builtin.assert:
        that:
          - "{{ nic | length > 0 }}"

    - name: Call assertion
      ansible.builtin.include_tasks: ../../tests/asserts/nic_assert.yml
      with_items: "{{ nic }}"
      loop_control:
        loop_var: nic_data
      when: nic | length > 0
