- name: Fetching Power Supply info
  ansible.builtin.uri:
    url: "https://{{ hostname }}{{ api_chassis }}/PowerSubsystem/PowerSupplies/{{ powersupply_data.Id }}"
    validate_certs: "{{ validate_certs }}"
    ca_path: "{{ ca_path | default(omit) }}"
    method: "{{ uri_method }}"
    user: "{{ username }}"
    password: "{{ password }}"
    headers: "{{ uri_headers }}"
    body_format: "{{ uri_body_format }}"
    status_code: "{{ uri_status_code }}"
    return_content: "{{ uri_return_content }}"
  register: powersupply_result
  no_log: true

- name: Set powersupply facts
  ansible.builtin.set_fact:
    api_response:
      "{{ powersupply_result.json | ansible.utils.remove_keys(target=['@odata.context',
      '@odata.id', '@odata.type', 'ActiveInputVoltage@Redfish.Deprecated', 'OperationalStatus@odata.count',
      'RedTypeOfSet@odata.count']) }}"

- name: Set the keys diff
  ansible.builtin.set_fact:
    diff_keys: "{{ powersupply_data.keys() | list | symmetric_difference((api_response.keys() | list)) }}"

- name: Set a diff of dict
  ansible.builtin.set_fact:
    diff_data: "{{ diff_data | combine({item: powersupply_data[item]}) }}"
  loop: "{{ powersupply_data.keys() }}"
  when:
    - diff_keys | length == 0
    - powersupply_data[item] != api_response[item]
    - item not in exclude_keys

- name: Assert the difference in Keys
  ansible.builtin.assert:
    that:
      - "{{ (diff_keys | length) == 0 }}"
      - "{{ (diff_data | length) == 0 }}"
    fail_msg: "The response from the role does not match | Diff Keys : {{ diff_keys }} Diff Data : {{ diff_data }}"
    success_msg: "The response from the role matches |  Diff Keys : {{ diff_keys }} Diff Data : {{ diff_data }}"
