galaxy_info:
  role_name: idrac_storage_controller
  author: |
    - Felix Stephen
    - Abhishek Sinha ('ABHISHEK-SINHA10')
  description: The role performs the iDRAC storage controller operations.
  company: Dell Technologies

  license: GPL-3.0-only

  min_ansible_version: "2.13"

  platforms:
    - name: EL
      versions:
        - "9"
        - "8"
    - name: Ubuntu
      versions:
        - jammy
    - name: SLES
      versions:
        - "15SP3"
        - "15SP4"

  galaxy_tags: []

dependencies: []
