hostname: "{{ inventory_hostname }}"
username: "username"
password: "password"

# Required for Export Role
idrac_ip: "{{ inventory_hostname }}"
idrac_user: "{{ username }}"
idrac_password: "{{ password }}"

validate_certs: false
proxy_params:
  server: 192.168.0.6
  port: 8080
  username: "proxy_user"
  password: "proxy_password"

repo_details:
  proto: "https"
  ip: "192.168.0.5"
  username: "username"
  password: "password"

http_url: "{{ repo_details.proto }}://{{ repo_details.ip }}/{{ http_path }}"
cifs_url: "//{{ repo_details.ip }}"
nfs_url: "{{ repo_details.ip }}:/{{ nfs_path }}"

gather_facts_target: "System"
