---
- hosts: hosts
  connection: local
  name: Configure the iDRAC timezone attributes
  gather_facts: False

  tasks:
  - name: Setup iDRAC Timezone
    dellemc_configure_idrac_timezone:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_pwd:  "{{ idrac_pwd }}"
       share_name: "{{ playbook_dir }}"
       setup_idrac_timezone: "Singapore"
       enable_ntp: "Disabled"
       ntp_server_1: "100.100.25.1"
       ntp_server_2: "100.100.26.2"
       ntp_server_3: "100.100.27.3"

    tags:
      - idrac_timezone