---
- name: Exporting the SCP components to HTTP
  dellemc.openmanage.idrac_server_config_profile:
    idrac_ip: "{{ idrac_ip }}"
    idrac_port: "{{ idrac_port }}"
    idrac_user: "{{ idrac_user }}"
    idrac_password: "{{ idrac_password }}"
    ca_path: "{{ ca_path | default(omit) }}"
    validate_certs: "{{ validate_certs }}"
    timeout: "{{ idrac_timeout }}"
    export_format: "{{ export_format }}"
    export_use: "{{ export_use }}"
    include_in_export: "{{ include_in_export }}"
    share_user: "{{ share_parameters.share_user | default(omit) }}"
    share_password: "{{ share_parameters.share_password | default(omit) }}"
    share_name: "{{ share_parameters.share_name }}"
    scp_file: "{{ share_parameters.scp_file | default(omit) }}"
    target: "{{ target }}"
    proxy_support: "{{ share_parameters.proxy_support | default(omit) }}"
    proxy_type: "{{ share_parameters.proxy_type | default(omit) }}"
    proxy_server: "{{ share_parameters.proxy_server | default(omit) }}"
    proxy_port: "{{ share_parameters.proxy_port | default(omit) }}"
    proxy_username: "{{ share_parameters.proxy_username | default(omit) }}"
    proxy_password: "{{ share_parameters.proxy_password | default(omit) }}"
    job_wait: "{{ idrac_export_server_config_profile_job_wait }}"
  register: out_scp
  delegate_to: "{{ idrac_export_server_config_profile_delegate }}"
