---
- name: Exporting the SCP components to local
  dellemc.openmanage.idrac_server_config_profile:
    idrac_ip: "{{ idrac_ip }}"
    idrac_port: "{{ idrac_port }}"
    idrac_user: "{{ idrac_user }}"
    idrac_password: "{{ idrac_password }}"
    ca_path: "{{ ca_path | default(omit) }}"
    validate_certs: "{{ validate_certs }}"
    timeout: "{{ idrac_timeout }}"
    export_format: "{{ export_format }}"
    export_use: "{{ export_use }}"
    include_in_export: "{{ include_in_export }}"
    share_name: "{{ share_parameters.share_name }}"
    target: "{{ target }}"
    scp_file: "{{ share_parameters.scp_file | default(omit) }}"
    job_wait: "{{ idrac_export_server_config_profile_job_wait }}"
  register: out_scp
  delegate_to: "{{ idrac_export_server_config_profile_delegate }}"
