---
- name: Get PCIeDevice information.
  ansible.builtin.uri:
    url: "https://{{ hostname }}{{ api_chassis }}/PCIeDevices?$expand=*($levels=1)"
    validate_certs: "{{ validate_certs }}"
    ca_path: "{{ ca_path | default(omit) }}"
    method: "{{ uri_method }}"
    user: "{{ username }}"
    password: "{{ password }}"
    headers: "{{ uri_headers }}"
    body_format: "{{ uri_body_format }}"
    status_code: "{{ uri_status_code }}"
    return_content: "{{ uri_return_content }}"
  register: pcie_result
  delegate_to: "{{ lookup('ansible.builtin.env', 'RUNON', default='localhost') }}"
  no_log: true

- name: Set PCIeDevice facts
  ansible.builtin.set_fact:
    pcie_device: "{{ pcie_result.json.Members | ansible.utils.remove_keys(target=['@odata.context', '@odata.id', '@odata.type', 'Links', '@odata.etag']) }}"
