---
- hosts: idrac
  connection: local
  name: Get system inventory
  gather_facts: False

  collections:
    - dellemc.openmanage

  tasks:
  - name: Get system inventory
    dellemc_get_system_inventory:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"
