---
- hosts: idrac
  connection: local
  name: Configure System lockdown mode
  gather_facts: False

  collections:
    - dellemc.openmanage

  tasks:
  - name: Configure System lockdown mode
    dellemc_system_lockdown_mode:
      idrac_ip:   "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password:  "{{ idrac_password }}"
      ca_path: "/path/to/ca_cert.pem"
      lockdown_mode: "Disabled"