---
- hosts: idrac
  connection: local
  name: Configure iDRAC CSIOR Setting
  gather_facts: False

  tasks:
  - name: Configure iDRAC CSIOR Setting
    dellemc_idrac_lc_attributes:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"
       share_name: "{{ playbook_dir }}"
       csior: "Enabled"
