---
- hosts: idrac
  connection: local
  name: Configure the boot order settings
  gather_facts: False

  collections:
    - dellemc.openmanage

  tasks:

  - name: Configure the system boot options settings.
    idrac_boot:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      ca_path: "/path/to/ca_cert.pem"
      boot_options:
        - display_name: Hard drive C
          enabled: true
        - boot_option_reference: NIC.PxeDevice.2-1
          enabled: true
    tags: boot-option

  - name: Configure the boot order settings.
    idrac_boot:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      ca_path: "/path/to/ca_cert.pem"
      boot_order:
        - Boot0001
        - Boot0002
        - Boot0004
        - Boot0003
    tags: boot-order

  - name: Configure the boot source override mode.
    idrac_boot:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      ca_path: "/path/to/ca_cert.pem"
      boot_source_override_mode: legacy
      boot_source_override_target: cd
      boot_source_override_enabled: once
    tags: boot-mode

  - name: Configure the UEFI target settings.
    idrac_boot:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      ca_path: "/path/to/ca_cert.pem"
      boot_source_override_mode: uefi
      boot_source_override_target: uefi_target
      uefi_target_boot_source_override: "VenHw(3A191845-5F86-4E78-8FCE-C4CFF59F9DAA)"
    tags: uefi-target

  - name: Configure the boot source override mode as pxe.
    idrac_boot:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      ca_path: "/path/to/ca_cert.pem"
      boot_source_override_mode: legacy
      boot_source_override_target: pxe
      boot_source_override_enabled: continuous
    tags: pxe-boot-mode
