---
- hosts: idrac
  connection: local
  name: Export Lifecycle Controller Logs
  gather_facts: False

  collections:
    - dellemc.openmanage

  tasks:
  - name: Export Lifecycle Controller Logs
    idrac_lifecycle_controller_logs:
       idrac_ip: "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password: "{{ idrac_password }}"
       share_name: "{{ playbook_dir }}"
       job_wait: "True"