---
- name: Export Lifecycle Controller Logs
  hosts: idrac
  gather_facts: false

  tasks:
    - name: Export Lifecycle Controller Logs
      dellemc.openmanage.idrac_lifecycle_controller_logs:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        ca_path: "/path/to/ca_cert.pem"
        share_name: "{{ playbook_dir }}"
        job_wait: true
      delegate_to: localhost
