---
- name: Dell OpenManage Ansible device inventory details.
  hosts: ome
  gather_facts: false

  tasks:
    - name: Retrieve basic inventory of all devices.
      dellemc.openmanage.ome_device_info:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "/path/to/ca_cert.pem"
      delegate_to: localhost

    - name: Retrieve basic inventory for devices identified by IDs 33333 or 11111 using filtering.
      dellemc.openmanage.ome_device_info:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "/path/to/ca_cert.pem"
        fact_subset: "basic_inventory"
        system_query_options:
          filter: "Id eq 33333 or Id eq 11111"
      delegate_to: localhost

    - name: Retrieve inventory details of specified devices identified by IDs 11111 and 22222.
      dellemc.openmanage.ome_device_info:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "/path/to/ca_cert.pem"
        fact_subset: "detailed_inventory"
        system_query_options:
          device_id:
            - 11111
            - 22222
      delegate_to: localhost

    - name: Retrieve inventory details of specified devices identified by service tags MXL1234 and MXL4567.
      dellemc.openmanage.ome_device_info:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "/path/to/ca_cert.pem"
        fact_subset: "detailed_inventory"
        system_query_options:
          device_service_tag:
            - MXL1234
            - MXL4567
      delegate_to: localhost

    - name: Retrieve details of specified inventory type of specified devices identified by ID and service tags.
      dellemc.openmanage.ome_device_info:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "/path/to/ca_cert.pem"
        fact_subset: "detailed_inventory"
        system_query_options:
          device_id:
            - 11111
          device_service_tag:
            - MXL1234
            - MXL4567
          inventory_type: "serverDeviceCards"
      delegate_to: localhost

    - name: Retrieve subsystem health of specified devices identified by service tags.
      dellemc.openmanage.ome_device_info:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "/path/to/ca_cert.pem"
        fact_subset: "subsystem_health"
        system_query_options:
          device_service_tag:
            - MXL1234
            - MXL4567
      delegate_to: localhost
