---
- hosts: ome
  connection: local
  name: Dell OpenManage Ansible Group configuration.
  gather_facts: False

  collections:
    - dellemc.openmanage

  tasks:
    - name: Create a new device group
      ome_groups:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "/path/to/ca_cert.pem"
        name: "group 1"
        description: "Group 1 description"
        parent_group_name: "group parent 1"
      tags:
        - create_group

    - name: Modify a device group using the group ID
      ome_groups:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "/path/to/ca_cert.pem"
        group_id: 1234
        description: "Group description updated"
        parent_group_name: "group parent 2"
      tags:
        - modify_group

    - name: Delete a device group using the device group name
      ome_groups:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "/path/to/ca_cert.pem"
        state: absent
        name: "group 1"
      tags:
        - delete_name

    - name: Delete multiple device groups using the group IDs
      ome_groups:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "/path/to/ca_cert.pem"
        state: absent
        group_id:
          - 1234
          - 5678
      tags:
        - delete_ids
