---
- hosts: ome
  connection: local
  name: OpenManage Ansible Modules
  gather_facts: false
  collections: dellemc.openmanage

  tasks:

  - name: Update device location settings of a chassis using the device ID.
    ome_device_location:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      ca_path: "/path/to/ca_cert.pem"
      device_id: 25011
      data_center: data center 1
      room: room 1
      aisle: aisle 1
      rack: rack 1
      rack_slot: 2
      location: location 1
    tags: location-device-id

  - name: Update device location settings of a chassis using the device service tag.
    ome_device_location:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      ca_path: "/path/to/ca_cert.pem"
      device_service_tag: GHRT2RL
      data_center: data center 1
      room: room 1
      aisle: aisle 1
      rack: rack 1
      rack_slot: 2
      location: location 1
    tags: location-device-service-tag

  - name: Update device location settings of the host chassis.
    ome_device_location:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      ca_path: "/path/to/ca_cert.pem"
      data_center: data center 1
      room: room 1
      aisle: aisle 1
      rack: rack 1
      rack_slot: 2
      location: location 1
    tags: location-chassis
