galaxy_info:
  author: |
    "Kritika-Bhateja
    Lovepreet-Singh"
  description: The role helps to manage the storage volume configuration.
  company: Dell Technologies
  license: GPL-3.0-only
  min_ansible_version: "2.13"
  platforms:
    - name: EL
      versions:
        - "9"
        - "8"
    - name: Ubuntu
      versions:
        - jammy
    - name: SLES
      versions:
        - "15SP3"
        - "15SP4"
  galaxy_tags: []
dependencies: []
