---
- hosts: ome
  connection: local
  name: Dell OpenManage Ansible device Template service.
  gather_facts: False

  collections:
    - dellemc.openmanage

  tasks:
  - name: get template with filter option.
    register: result
    failed_when: "'template_info' not in result or result.template_info['{{hostname}}']['@odata.count'] == 0"
    ome_template_info:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        ca_path: "/path/to/ca_cert.pem"
        system_query_options:
           filter: "Name eq 'template_name'"
  - name: get specific template from result
    with_subelements:
        - "{{ result.template_info }}"
        - value
    debug:
       msg: "{{item.1}}"
    when: item.1['Name']=='template_name' 
