---
- name: Configure iDRAC CSIOR Setting
  hosts: idrac
  gather_facts: false

  tasks:
    - name: Configure iDRAC CSIOR Setting
      dellemc.openmanage.dellemc_idrac_lc_attributes:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        ca_path: "/path/to/ca_cert.pem"
        csior: "Enabled"
      delegate_to: localhost
