---
- name: Converge file to update attributes with apply time as Immediate
  hosts: all
  gather_facts: false
  tasks:
    - name: Making sure Server is powered on and clear all job
      ansible.builtin.include_tasks:
        file: ../helper/common/power_on_idrac_and_clear_all_job.yaml

    - name: Include the helper file
      ansible.builtin.include_tasks: ../__helper.yaml
      vars:
        initial_state: true

    - name: Pre-check - fail if enough disk not found to create VD on RAID 0
      ansible.builtin.fail:
        msg: 'Physical disks are not sufficient to proceed the test case need
             more than 1 and found {{ physicaldisks | length }}'
      when: physicaldisks is defined and physicaldisks | length < 1

    - name: Pre-Req - Creating the VD
      ansible.builtin.include_tasks: ../__helper.yaml
      vars:
        volume_type: "RAID 0"
        span_length: 1
        vd_trigger: 1
        id: ["{{ physicaldisks[0] }}"]
        reset_trigger: 1
        ignore_errors_val: true
