---
- hosts: ome
  connection: local
  name: Dell OME Application network webserver settings.
  gather_facts: False

  collections:
    - dellemc.openmanage

  tasks:
  - name: Update webserver port and session time out configuration.
    ome_application_network_webserver:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      webserver_port: 443
      webserver_timeout: 10
    tags:
      - port_timeout_update

  - name: Update session time out
    ome_application_network_webserver:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      webserver_timeout: 30
    tags:
      - timeout_update

  - name: Update web server port.
    ome_application_network_webserver:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      webserver_port: 8443
    tags:
      - port_update